spring:
  jpa:
    open-in-view: false
    show-sql: true
    
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
  #        hibernate:
  #          ddl-auto: create
  
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/be6_3runner_coupon
    username: be6_3runner
    password: tHos2g5st4@XH7mT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 20
      max-idle: 20
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1
  
  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!
  
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-coupon

server:
  shutdown: graceful

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /coupon/docs/swagger